# Generated by Django 5.2.8 on 2025-11-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="agreement_accepted",
        ),
    ]
