# Generated by Django 5.2.8 on 2025-12-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
    ]
