# Generated by Django 5.2.8 on 2025-11-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_place_placeitem_zone_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["item_code"]},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="placeitem",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.AlterField(
            model_name="place",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="warehouse.zone",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="warehouse.stock",
            ),
        ),
    ]
