# Generated by Django 5.2.8 on 2025-11-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_item_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeitem",
            name="STATUS",
            field=models.CharField(
                choices=[
                    ("ok", "normal"),
                    ("blk", "block"),
                    ("no", "absent"),
                    ("new", "new"),
                    ("dock", "registration"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
