# Generated by Django 5.2.8 on 2025-11-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_placeitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeitem",
            name="STATUS",
            field=models.CharField(
                choices=[
                    ("ok", "ok"),
                    ("blk", "blk"),
                    ("no", "no"),
                    ("new", "new"),
                    ("dock", "dock"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
