# Generated by Django 5.2.8 on 2025-12-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0017_rename_status_placeitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbound", "inbound"),
                    ("outbound", "outbound"),
                    ("blk", "block"),
                    ("new", "new"),
                    ("ok", "ok"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
